### ISSUE TITLE
Search Function (JavaScript)

### ISSUE THREAD

**Issue by orlandokennycs** [FSUInnovationHub/CreatorConnect#33]
Fix the search function in index.html.

**Comment by Azure-Agst** [comment]
Heads up: Eventually, `/getUsers/<count>` will be depreciated and the API will not serve more than 9 users per request, in order to save bandwidth. We'll implement an endpoint for the apt that searches the database depending on the URL variables passed. I wouldn't get too invested in implementing a client-side search since it's going to change real soon.
